### ISSUE TITLE
“Compilation failed: Unknown option: --multi-dex” when enabling Multi-Dex

### ISSUE THREAD

**Issue by wiwski** [atsushieno/xamarin-android-d8-build#1]
It seems that building fail when enabling the MultiDex option, which makes sense. Is there any workaround? 
I'm getting the following error, but I don't know how to solve it with the use of this package : 
`Error:Cannot fit requested classes in a single dex file.Try supplying a main-dex list. `

**Comment by atsushieno** [comment]
Xamarin guys are working on d8, r8 and co. Check xamarin/xamarin-android repo.
